name: dia_app
description: "Your daily agenda app."
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  mockito: ^5.5.1
  build_runner: ^2.10.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  firebase_auth: ^6.1.1
  google_fonts: ^6.3.3
  url_launcher: ^6.3.1
  provider: ^6.1.5+1
  package_info_plus: ^9.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

